<?php

namespace Database\Seeders;

use App\Models\Category;
use Illuminate\Database\Seeder;

class CategorySeeder extends Seeder
{
    public function run(): void
    {
        // All 14 categories based on product folder structure
        $categories = [
            [
                'name' => 'Kitchen Hoods',
                'slug' => 'kitchen-hoods',
                'description' => 'Premium built-in kitchen hoods with powerful airflow up to 1500 m³/h. Features include touch control, auto-clean, and energy-efficient BLDC motors.',
                'features' => [
                    'Premium Quality',
                    'BLDC Copper Motor',
                    '1 Year Warranty',
                    'Energy Efficient',
                    'Heat + Auto Clean',
                    'Gesture and Touch Control',
                    'Inverter Technology A+++ Rated',
                    'Low Noise Level',
                ],
                'image' => '/images/products/kitchen-hoods/FKH-H90-06S/1.webp',
                'icon' => 'kitchen-hood',
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 1,
            ],
            [
                'name' => 'Kitchen Hobs',
                'slug' => 'kitchen-hobs',
                'description' => 'Built-in kitchen hobs with tempered glass or stainless steel panels. Available in 3 to 5 burner configurations with brass burners and flame failure devices.',
                'features' => [
                    'Complete Brass Burners',
                    'Sabaf Burners',
                    'EPS Burners',
                    'Tempered Glass',
                    'Flame Failure Device',
                    'Stainless Steel Finish',
                    '5KW Powerful Burners',
                    'Immediate Auto Ignition',
                ],
                'image' => '/images/products/kitchen-hobs/FBH-SS90-5SBF/1.webp',
                'icon' => 'kitchen-hob',
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 2,
            ],
            [
                'name' => 'Cooking Ranges',
                'slug' => 'cooking-ranges',
                'description' => 'Professional cooking ranges with 3 to 5 burners. Perfect for modern kitchens with complete brass burners and stainless steel finish.',
                'features' => [
                    'Complete Brass Burners',
                    'Sabaf Burners',
                    'Tempered Glass',
                    'Flame Failure Device',
                    'Stainless Steel Finish',
                    '5KW Powerful Burners',
                    'Immediate Auto Ignition',
                    'Multiple Size Options',
                ],
                'image' => '/images/products/cooking-ranges/fcr-5bb.webp',
                'icon' => 'cooking-range',
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 3,
            ],
            [
                'name' => 'Oven Toasters',
                'slug' => 'oven-toasters',
                'description' => 'Digital and mechanical oven toasters with capacities from 35L to 48L. Features include rotisserie function and convection heating.',
                'features' => [
                    'Double Layered Glass Door',
                    'Inner Lamp',
                    'Rotisserie Function',
                    'Convection Function',
                    'Stainless Steel Elements',
                    'Digital Controls',
                    'Large Capacity',
                ],
                'image' => '/images/products/oven-toasters/FOT-2501C/1.webp',
                'icon' => 'oven',
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 4,
            ],
            [
                'name' => 'Air Fryers',
                'slug' => 'air-fryers',
                'description' => 'Digital air fryers with capacities from 4L to 8L for healthy oil-free cooking. Features dual heating elements for even temperature control.',
                'features' => [
                    'Oil-Free Cooking',
                    'Digital Touch Panel',
                    'Wide Temperature Control',
                    'Injection Molding Texture',
                    'Non-Stick Coating',
                    'Dual Heating Element',
                    'Large Capacity',
                ],
                'image' => '/images/products/air-fryers/FAF-801WD/1.webp',
                'icon' => 'air-fryer',
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 5,
            ],
            [
                'name' => 'Water Coolers',
                'slug' => 'water-coolers',
                'description' => 'Commercial and industrial electric water coolers with capacities from 35L to 300L. Made with food-grade stainless steel.',
                'features' => [
                    'Adjustable Thermostat',
                    'Food Grade Stainless Steel',
                    'High Back Pressure Compressor',
                    'Spring Loaded Push Button',
                    'Non-Magnetic Heavy Gauge',
                    'Brand New Compressor with Condenser',
                ],
                'image' => '/images/products/water-coolers/water-cooler-35ltr.webp',
                'icon' => 'water-cooler',
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 6,
            ],
            [
                'name' => 'Slim Water Coolers',
                'slug' => 'slim-water-coolers',
                'description' => 'Space-saving slim design water coolers perfect for compact spaces. Available in 35L, 45L, and 65L capacities.',
                'features' => [
                    'Space-Saving Design',
                    'Adjustable Thermostat',
                    'Food Grade Stainless Steel',
                    'High Back Pressure Compressor',
                    'Compact Footprint',
                ],
                'image' => '/images/products/slim-water-coolers/fe-35-slim.webp',
                'icon' => 'slim-cooler',
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 7,
            ],
            [
                'name' => 'Storage Coolers',
                'slug' => 'storage-coolers',
                'description' => 'Self-contained storage water coolers with large capacity from 25L to 1000L. Ideal for high-demand environments.',
                'features' => [
                    'Food Grade Stainless Steel Tanks',
                    'Brand New Compressors',
                    'Copper Fan Motors',
                    'Large Storage Capacity',
                    'Heavy Duty Construction',
                ],
                'image' => '/images/products/storage-coolers/fst-200.webp',
                'icon' => 'storage-cooler',
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 8,
            ],
            [
                'name' => 'Water Dispensers',
                'slug' => 'water-dispensers',
                'description' => 'Compact water dispensers for home and office use. Features food-grade stainless steel tanks and eco-friendly refrigerants.',
                'features' => [
                    'Food-Grade Stainless Steel Tanks',
                    'Eco-Friendly Refrigerants',
                    '100% Copper Coiling',
                    'Hot & Cold Functions',
                    'Compact Design',
                ],
                'image' => '/images/products/water-dispensers/1.webp',
                'icon' => 'dispenser',
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 9,
            ],
            [
                'name' => 'Water Heaters',
                'slug' => 'water-heaters',
                'description' => 'Electric water heaters with Eco Watt technology for energy-efficient water heating. Various capacities available.',
                'features' => [
                    'Eco Watt Technology',
                    'Energy Efficient',
                    'Overheating Protection',
                    'Fully Insulated',
                    'Incoloy 840 Heating Element',
                ],
                'image' => '/images/products/water-heaters/Eco Watt Series Electric Water Heater.webp',
                'icon' => 'electric-geyser',
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 10,
            ],
            [
                'name' => 'Fast Electric Water Heaters',
                'slug' => 'fast-electric-water-heaters',
                'description' => 'Fast electric water heaters from 30 to 200 liters with adjustable wattage options and thermal safety cutouts.',
                'features' => [
                    'Single Welded Tanks',
                    'Adjustable Wattage Options',
                    'Thermal Safety Cutouts',
                    'Full Insulation',
                    'Incoloy 840 Heating Element',
                    'Fast Heating Technology',
                ],
                'image' => '/images/products/fast-electric-water-heaters/ffeg-f100.webp',
                'icon' => 'fast-geyser',
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 11,
            ],
            [
                'name' => 'Instant Electric Water Heaters',
                'slug' => 'instant-electric-water-heaters',
                'description' => 'Instant cum storage electric water heaters from 10 to 60 liters with quick heating technology and compact design.',
                'features' => [
                    'Quick Heating Technology',
                    'Compact Design',
                    'Overheating Protection',
                    'Wattage Control',
                    'Fully Insulated',
                    'Instant Hot Water',
                ],
                'image' => '/images/products/instant-electric-water-heaters/fiewhs-25l.webp',
                'icon' => 'instant-geyser',
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 12,
            ],
            [
                'name' => 'Hybrid Geysers',
                'slug' => 'hybrid-geysers',
                'description' => 'Hybrid water heaters with both electric and gas heating options for dual fuel flexibility. Capacities from 25 to 100 gallons.',
                'features' => [
                    'Dual Fuel Flexibility',
                    'Overheating Protection',
                    'Wattage Control',
                    'Fully Insulated',
                    'Accurate Volume Capacity',
                    'Incoloy 840 Heating Element',
                ],
                'image' => '/images/products/hybrid-geysers/fhg-65g.webp',
                'icon' => 'hybrid-geyser',
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 13,
            ],
            [
                'name' => 'Accessories',
                'slug' => 'accessories',
                'description' => 'Kitchen and appliance accessories including basket liners, iron racks, and replacement parts.',
                'features' => [
                    'Durable Materials',
                    'Compatible with Fischer Products',
                    'Affordable Prices',
                    'Easy Installation',
                ],
                'image' => '/images/products/accessories/fac-bl2.webp',
                'icon' => 'accessories',
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 14,
            ],
        ];

        // Create all categories (all as parent categories, no hierarchy)
        foreach ($categories as $category) {
            Category::updateOrCreate(
                ['slug' => $category['slug']],
                array_merge($category, ['parent_id' => null])
            );
        }

        // Delete old categories that don't match our new structure
        Category::whereNotIn('slug', [
            'kitchen-hoods',
            'kitchen-hobs',
            'cooking-ranges',
            'oven-toasters',
            'air-fryers',
            'water-coolers',
            'slim-water-coolers',
            'storage-coolers',
            'water-dispensers',
            'water-heaters',
            'fast-electric-water-heaters',
            'instant-electric-water-heaters',
            'hybrid-geysers',
            'accessories',
        ])->delete();
    }
}
