<?php

namespace Database\Seeders;

use App\Models\Category;
use Illuminate\Database\Seeder;

class CategorySeeder extends Seeder
{
    public function run(): void
    {
        $categories = [
            // Kitchen Appliances
            [
                'name' => 'Kitchen Hoods',
                'slug' => 'kitchen-hoods',
                'description' => 'Premium kitchen hoods with powerful airflow up to 1500 m³/h.',
                'features' => [
                    'Premium Quality',
                    'BLDC Copper Motor',
                    '1 Year Warranty',
                    'Energy Efficient',
                    'Heat + Auto Clean',
                    'Gesture and Touch Control',
                    'Inverter Technology A+++ Rated',
                    'Low Noise Level',
                ],
                'image' => '/images/categories/kitchen-hoods.png',
                'icon' => 'kitchen-hood',
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 1,
            ],
            [
                'name' => 'Kitchen Hobs',
                'slug' => 'kitchen-hobs',
                'description' => 'Built-in kitchen hobs with tempered glass or stainless steel panels.',
                'features' => [
                    'Complete Brass Burners',
                    'Sabaf Burners',
                    'EPS Burners',
                    'Tempered Glass',
                    'Flame Failure Device',
                    'Stainless Steel Finish',
                    '5KW Powerful Burners',
                    'Immediate Auto Ignition',
                ],
                'image' => '/images/categories/kitchen-hobs.png',
                'icon' => 'kitchen-hob',
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 2,
            ],
            [
                'name' => 'Oven Toasters',
                'slug' => 'oven-toasters',
                'description' => 'Digital and mechanical oven toasters with capacities from 35L to 48L.',
                'features' => [
                    'Double Layered Glass Door',
                    'Inner Lamp',
                    'Rotisserie Function',
                    'Convection Function',
                    'Stainless Steel Elements',
                ],
                'image' => '/images/categories/oven-toasters.png',
                'icon' => 'oven',
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 3,
            ],
            [
                'name' => 'Air Fryers',
                'slug' => 'air-fryers',
                'description' => 'Digital air fryers with capacities from 4L to 8L for healthy oil-free cooking.',
                'features' => [
                    'Digital Touch Panel',
                    'Wide Temperature Control',
                    'Injection Molding Texture',
                    'Non-Stick Coating',
                    'Bottom Heater for Even Temperature Control',
                ],
                'image' => '/images/categories/air-fryers.png',
                'icon' => 'air-fryer',
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 4,
            ],
            [
                'name' => 'Cooking Ranges',
                'slug' => 'cooking-ranges',
                'description' => 'Professional cooking ranges with 3 to 5 burners.',
                'features' => [
                    'Complete Brass Burners',
                    'Sabaf Burners',
                    'Tempered Glass',
                    'Flame Failure Device',
                    'Stainless Steel Finish',
                    '5KW Powerful Burners',
                    'Immediate Auto Ignition',
                    'Multiple Size Options',
                ],
                'image' => '/images/categories/cooking-ranges.png',
                'icon' => 'cooking-range',
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 5,
            ],
            [
                'name' => 'Blenders & Processors',
                'slug' => 'blenders-processors',
                'description' => 'Multi-function food processors and blenders for your kitchen.',
                'features' => [
                    'Multi-Function Food Processing',
                    'Precision Stainless Steel Blades & Discs',
                    'Pulse & Speed Control',
                    'Generous Capacity',
                ],
                'image' => '/images/categories/blenders-processors.png',
                'icon' => 'blender',
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 6,
            ],
            // Water Heating
            [
                'name' => 'Geysers & Heaters',
                'slug' => 'geysers-heaters',
                'description' => 'Water geysers and heaters with various capacities.',
                'features' => [
                    'Overheating Protection',
                    'Wattage Control',
                    'Fully Insulated',
                    'Accurate Volume Capacity',
                    'Incoloy 840 Heating Element',
                    'Imported Brass Safety Valves',
                ],
                'image' => '/images/categories/geysers-heaters.png',
                'icon' => 'gas-geyser',
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 7,
            ],
            [
                'name' => 'Gas Water Heaters',
                'slug' => 'gas-water-heaters',
                'description' => 'Instant gas water heaters with capacities from 15 to 55 gallons.',
                'features' => [
                    'Overheating Protection',
                    'Wattage Control',
                    'Fully Insulated',
                    'Accurate Volume Capacity',
                    'Copper Heat Exchangers',
                    'Digital Temperature Control',
                ],
                'image' => '/images/categories/gas-water-heaters.png',
                'icon' => 'gas-geyser',
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 8,
            ],
            [
                'name' => 'Electric + Gas Geysers',
                'slug' => 'hybrid-geysers',
                'description' => 'Hybrid water heaters with both electric and gas heating options.',
                'features' => [
                    'Dual Fuel Flexibility',
                    'Overheating Protection',
                    'Wattage Control',
                    'Fully Insulated',
                    'Accurate Volume Capacity',
                    'Incoloy 840 Heating Element',
                ],
                'image' => '/images/categories/hybrid-geysers.png',
                'icon' => 'hybrid-geyser',
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 9,
            ],
            [
                'name' => 'Fast Electric Water Heaters',
                'slug' => 'fast-electric-water-heaters',
                'description' => 'Fast electric water heaters from 30 to 200 liters.',
                'features' => [
                    'Single Welded Tanks',
                    'Adjustable Wattage Options',
                    'Thermal Safety Cutouts',
                    'Full Insulation',
                    'Incoloy 840 Heating Element',
                ],
                'image' => '/images/categories/electric-water-heaters.png',
                'icon' => 'electric-geyser',
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 10,
            ],
            [
                'name' => 'Instant Electric Water Heaters',
                'slug' => 'instant-electric-water-heaters',
                'description' => 'Instant cum storage electric water heaters from 10 to 60 liters.',
                'features' => [
                    'Quick Heating Technology',
                    'Compact Design',
                    'Overheating Protection',
                    'Wattage Control',
                    'Fully Insulated',
                ],
                'image' => '/images/categories/instant-water-heaters.png',
                'icon' => 'instant-geyser',
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 11,
            ],
            // Water Cooling
            [
                'name' => 'Water Coolers',
                'slug' => 'water-coolers',
                'description' => 'Commercial and industrial electric water coolers.',
                'features' => [
                    'Adjustable Thermostat',
                    'Food Grade Non Magnetic Heavy Gauge Stainless Steel',
                    'High Back Pressure Compressor with Condenser',
                    'Spring Loaded Push Button',
                ],
                'image' => '/images/categories/water-coolers.png',
                'icon' => 'water-cooler',
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 12,
            ],
            [
                'name' => 'Slim Electric Water Coolers',
                'slug' => 'slim-water-coolers',
                'description' => 'Space-saving slim design water coolers.',
                'features' => [
                    'Space-Saving Design',
                    'Adjustable Thermostat',
                    'Food Grade Stainless Steel',
                    'High Back Pressure Compressor',
                ],
                'image' => '/images/categories/slim-water-coolers.png',
                'icon' => 'slim-cooler',
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 13,
            ],
            [
                'name' => 'Water Dispensers',
                'slug' => 'water-dispensers',
                'description' => 'Compact water dispensers for home and office use.',
                'features' => [
                    'Food-Grade Stainless Steel Tanks',
                    'Eco-Friendly Refrigerants',
                    '100% Copper Coiling',
                ],
                'image' => '/images/categories/water-dispensers.png',
                'icon' => 'dispenser',
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 14,
            ],
            [
                'name' => 'Self-Contained Storage Coolers',
                'slug' => 'storage-type-water-coolers',
                'description' => 'Premium storage capacity water coolers from 25 to 1000 liters.',
                'features' => [
                    'Food Grade Stainless Steel Tanks',
                    'Brand New Compressors',
                    'Copper Fan Motors',
                    'Large Storage Capacity',
                ],
                'image' => '/images/categories/storage-coolers.png',
                'icon' => 'storage-cooler',
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 15,
            ],
            // Room Coolers - NEW
            [
                'name' => 'Room Coolers',
                'slug' => 'room-coolers',
                'description' => 'Efficient room coolers for comfortable indoor cooling.',
                'features' => [
                    'Powerful Air Throw',
                    'Honeycomb Cooling Pads',
                    'Large Water Tank Capacity',
                    'Multiple Speed Settings',
                    'Energy Efficient',
                ],
                'image' => '/images/categories/room-coolers.png',
                'icon' => 'room-cooler',
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 16,
            ],
        ];

        foreach ($categories as $category) {
            Category::updateOrCreate(
                ['slug' => $category['slug']],
                $category
            );
        }

        // Delete old Accessories category if it exists (replaced by Blenders & Processors)
        Category::where('slug', 'accessories')->delete();
    }
}
